version: '2'

services:
  server:
    image: wiremockdemo
    container_name: app
    ports:
      - 3000:3000
    links:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/statCollection
      - SPRING_DATASOURCE_USER=statCollection
      - SPRING_DATASOURCE_PASSWORD=root
  mock:
    image: mockmockmock
    container_name: mock
    ports:
      - 8080:8000
  db:
    image: postgres:14.4
    container_name: db
    environment:
      - POSTGRES_USER=statCollection
      - POSTGRES_PASSWORD=root
    ports:
      - 5432:5432
